apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-nordeste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-nordeste
  template:
    metadata:
      labels:
        app: sensor-nordeste
    spec:
      nodeSelector:
        region: nordeste
      containers:
        - name: sensor
          image: janssencristian/sensor:1.0
          env:
            - name: EDGE_URL
              value: http://edge-nordeste-service:8000